services:

  postgres:
    image: postgres:16-alpine
    container_name: glog-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: glog_user
      POSTGRES_PASSWORD: glog_password
      POSTGRES_DB: glog
    volumes:
      - glog-pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: glog-backend
    environment:
      - PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=glog_user
      - DB_PASSWORD=glog_password
      - DB_NAME=glog
    depends_on:
      - postgres

volumes:
  glog-pgdata: